#Containerfile_Assignment5
FROM fedora:latest
#removed tuxpaint and vim
RUN  yum -y install httpd
#create volume "data"
VOLUME data
#opening port 80 and running httpd
EXPOSE 80
ENTRYPOINT /usr/sbin/httpd -DFOREGROUND
